# Generated by Django 2.2.6 on 2019-12-08 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('post_time', models.DateTimeField()),
                ('downloads', models.IntegerField(default=0)),
                ('filepath', models.CharField(max_length=100)),
                ('ip', models.CharField(default='', max_length=32)),
                ('filesize', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'filesys',
            },
        ),
    ]
