# Generated by Django 2.2.6 on 2019-12-09 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filesys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='content',
        ),
        migrations.RemoveField(
            model_name='file',
            name='filepath',
        ),
        migrations.RemoveField(
            model_name='file',
            name='ip',
        ),
        migrations.AlterField(
            model_name='file',
            name='post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
