# Generated by Django 2.2.6 on 2019-12-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesys', '0002_auto_20191209_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filepath',
            field=models.CharField(default='static/file', max_length=100),
        ),
    ]
