# Generated by Django 2.2.6 on 2019-12-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesys', '0003_file_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filebrief',
            field=models.CharField(default='brief', max_length=100),
        ),
    ]
