# Generated by Django 2.2.6 on 2019-12-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesys', '0004_file_filebrief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='post_time',
            field=models.DateTimeField(),
        ),
    ]
